In [55]:
import matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sys, cv2, glob, os, time
import pandas as pd 
import io
import numpy as np
from keras.datasets import mnist
from keras.layers import Input, Dense, Reshape, Flatten,Activation
from keras.layers.advanced_activations import LeakyReLU
from keras.models import Sequential, Model
import numpy as np # linear algebra

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import os
import glob
import cv2
import tensorflow as tf
from keras import layers
from keras.layers import Dropout , Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
from sklearn.model_selection import train_test_split
import keras.backend as K
from sklearn.utils import shuffle
# importing all necessary libraries to run the code
import re,string
import numpy as np
import pandas as pd
import keras_metrics
import tensorflow.keras
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,Embedding
# using the variable sw to hold all stopwords that are in English
sw = stopwords.words('english')
import matplotlib.pyplot as plt

import numpy as np # linear algebra

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
import glob
import cv2
import tensorflow as tf
from keras import layers
from keras.layers import Dropout , Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
from sklearn.model_selection import train_test_split
import keras.backend as K
from sklearn.utils import shuffle
# importing all necessary libraries to run the code
import re,string
import numpy as np
import pandas as pd
import keras_metrics
import tensorflow.keras
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,Embedding


In [28]:
dataUN=pd.read_csv('UNSW_NB15_testing-set.csv')
dataUN1=pd.read_csv('UNSW_NB15_training-set.csv')

dataI=pd.read_csv('IoT Network Intrusion Dataset.csv')

In [29]:
dataUN1[:2]

id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0   1  0.000011   udp       -   INT      2      0     496       0   
1   2  0.000008   udp       -   INT      2      0    1762       0   

          rate  ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  \
0   90909.0902  ...                 1               2             0   
1  125000.0003  ...                 1               2             0   

   ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  \
0           0                 0           1           2                0   
1           0                 0           1           2                0   

   attack_cat  label  
0      Normal      0  
1      Normal      0  

[2 rows x 45 columns]

In [30]:
dataI[:2]

Flow_ID           Src_IP  Src_Port  \
0  192.168.0.13-192.168.0.16-10000-10101-17     192.168.0.13     10000   
1   192.168.0.13-222.160.179.132-554-2179-6  222.160.179.132      2179   

         Dst_IP  Dst_Port  Protocol               Timestamp  Flow_Duration  \
0  192.168.0.16     10101        17  25/07/2019 03:25:53 AM             75   
1  192.168.0.13       554         6  26/05/2019 10:11:06 PM           5310   

   Tot_Fwd_Pkts  Tot_Bwd_Pkts  ...  Active_Std  Active_Max  Active_Min  \
0             1             1  ...         0.0         0.0         0.0   
1             1             2  ...         0.0         0.0         0.0   

   Idle_Mean     Idle_Std  Idle_Max  Idle_Min    Label    Cat  \
0       75.0     0.000000      75.0      75.0  Anomaly  Mirai   
1     2655.0  2261.327486    4254.0    1056.0  Anomaly    DoS   

             Sub_Cat  
0  Mirai-Ackflooding  
1    DoS-Synflooding  

[2 rows x 86 columns]

In [31]:
dataF=dataUN.append(dataUN1,ignore_index = True) 

In [32]:
dataF[:2]

id       dur proto service state  spkts  dpkts  sbytes  dbytes       rate  \
0   1  0.121478   tcp       -   FIN      6      4     258     172  74.087490   
1   2  0.649902   tcp       -   FIN     14     38     734   42014  78.473372   

   ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  \
0  ...                 1               1             0           0   
1  ...                 1               2             0           0   

   ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  attack_cat  \
0                 0           1           1                0      Normal   
1                 0           1           6                0      Normal   

   label  
0      0  
1      0  

[2 rows x 45 columns]

In [33]:
from collections import Counter
Counter(dataI["Sub_Cat"])

Counter({'Mirai-Ackflooding': 55124,
         'DoS-Synflooding': 59391,
         'Scan Port OS': 53073,
         'Mirai-Hostbruteforceg': 121181,
         'Mirai-UDP Flooding': 183554,
         'Mirai-HTTP Flooding': 55818,
         'Normal': 40073,
         'Scan Hostport': 22192,
         'MITM ARP Spoofing': 35377})

In [34]:
from collections import Counter
Counter(dataF["attack_cat"])

Counter({'Normal': 93000,
         'Backdoor': 2329,
         'Analysis': 2677,
         'Fuzzers': 24246,
         'Shellcode': 1511,
         'Reconnaissance': 13987,
         'Exploits': 44525,
         'DoS': 16353,
         'Worms': 174,
         'Generic': 58871})

In [35]:
from collections import Counter
Counter(dataI["Label"])

Counter({'Anomaly': 585710, 'Normal': 40073})

In [36]:
dataF1=dataF.loc[dataF['attack_cat'] == "Normal"]
print(len(dataF1))
dataF2=dataF.loc[dataF['attack_cat'] == "Backdoor"]
print(len(dataF2))
dataF3=dataF.loc[dataF['attack_cat'] == "Analysis"]
print(len(dataF3))
dataF4=dataF.loc[dataF['attack_cat'] == "Fuzzers"]
print(len(dataF4))
dataF5=dataF.loc[dataF['attack_cat'] == "Shellcode"]
print(len(dataF5))
dataF6=dataF.loc[dataF['attack_cat'] == "Reconnaissance"]
print(len(dataF6))
dataF7=dataF.loc[dataF['attack_cat'] == "Exploits"]
print(len(dataF7))
dataF8=dataF.loc[dataF['attack_cat'] == "DoS"]
print(len(dataF8))
dataF9=dataF.loc[dataF['attack_cat'] == "Worms"]
print(len(dataF9))
dataF10=dataF.loc[dataF['attack_cat'] == "Generic"]
print(len(dataF10))



dataI1=dataI.loc[dataI['Sub_Cat'] == 'Mirai-Ackflooding']
print(len(dataI1))
dataI2=dataI.loc[dataI['Sub_Cat'] == 'DoS-Synflooding']
print(len(dataI2))
dataI3=dataI.loc[dataI['Sub_Cat'] == 'Scan Port OS']
print(len(dataI3))
dataI4=dataI.loc[dataI['Sub_Cat'] == 'Mirai-Hostbruteforceg']
print(len(dataI4))

dataI5=dataI.loc[dataI['Sub_Cat'] == 'Mirai-UDP Flooding']
print(len(dataI5))
dataI6=dataI.loc[dataI['Sub_Cat'] == 'Mirai-HTTP Flooding']
print(len(dataI6))

dataI7=dataI.loc[dataI['Sub_Cat'] == 'Scan Hostport']
print(len(dataI7))
dataI8=dataI.loc[dataI['Sub_Cat'] == 'MITM ARP Spoofing']
print(len(dataI8))

dataI9=dataI.loc[dataI['Sub_Cat'] == 'Normal']
print(len(dataI9))



93000
2329
2677
24246
1511
13987
44525
16353
174
58871
55124
59391
53073
121181
183554
55818
22192
35377
40073


In [37]:
dataF1=dataF1[0:170]
dataF2=dataF2[0:170]
dataF3=dataF3[0:170]
dataF4=dataF4[0:170]
dataF5=dataF5[0:170]
dataF6=dataF6[0:170]
dataF7=dataF7[0:170]
dataF8=dataF8[0:170]
dataF9=dataF9[0:170]
dataF10=dataF10[0:170]


dataI1=dataI1[0:170]
dataI2=dataI2[0:170]
dataI3=dataI3[0:170]
dataI4=dataI4[0:170]
dataI5=dataI5[0:170]
dataI6=dataI6[0:170]
dataI7=dataI7[0:170]
dataI8=dataI8[0:170]
dataI9=dataI9[0:170]


In [38]:
dataF=dataF1.append(dataF2,ignore_index = True)
dataF=dataF.append(dataF3,ignore_index = True) 
dataF=dataF.append(dataF4,ignore_index = True) 
dataF=dataF.append(dataF5,ignore_index = True) 
dataF=dataF.append(dataF6,ignore_index = True) 
dataF=dataF.append(dataF7,ignore_index = True) 
dataF=dataF.append(dataF8,ignore_index = True) 
dataF=dataF.append(dataF9,ignore_index = True) 
dataF=dataF.append(dataF10,ignore_index = True) 

dataI=dataI1.append(dataI2,ignore_index = True)
dataI=dataI.append(dataI3,ignore_index = True)
dataI=dataI.append(dataI4,ignore_index = True)
dataI=dataI.append(dataI5,ignore_index = True)
dataI=dataI.append(dataI6,ignore_index = True)
dataI=dataI.append(dataI7,ignore_index = True)
dataI=dataI.append(dataI8,ignore_index = True)
dataI=dataI.append(dataI9,ignore_index = True)

In [39]:
from collections import Counter
Counter(dataI["Label"])

Counter({'Anomaly': 1360, 'Normal': 170})

In [40]:
from collections import Counter
Counter(dataF["label"])

Counter({0: 170, 1: 1530})

In [41]:
dataF.rename(columns = {'label':'Label'}, inplace = True)
dataF.rename(columns = {'attack_cat':'Sub_Cat'}, inplace = True)

In [42]:
DataITarget=dataI[["Label","Cat","Sub_Cat"]]

dataIFeatures=dataI.drop(["Label","Cat","Sub_Cat"], axis=1)

DataFTarget=dataF[["Sub_Cat","Label"]]

dataFFeatures=dataF.drop(["Sub_Cat","Label"], axis=1)

In [43]:
DataITarget["Sub_Cat"]=DataITarget["Sub_Cat"].replace('Normal','Normal_I')

C:\Users\SOHAIL~1\AppData\Local\Temp/ipykernel_10848/4285179342.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DataITarget["Sub_Cat"]=DataITarget["Sub_Cat"].replace('Normal','Normal_I')


In [44]:
from collections import Counter
Counter(DataITarget["Sub_Cat"])

Counter({'Mirai-Ackflooding': 170,
         'DoS-Synflooding': 170,
         'Scan Port OS': 170,
         'Mirai-Hostbruteforceg': 170,
         'Mirai-UDP Flooding': 170,
         'Mirai-HTTP Flooding': 170,
         'Scan Hostport': 170,
         'MITM ARP Spoofing': 170,
         'Normal_I': 170})

In [45]:
from sklearn import preprocessing 
from sklearn.preprocessing import LabelEncoder
le = preprocessing.LabelEncoder()

dataIFeatures=dataIFeatures.apply(LabelEncoder().fit_transform)

In [46]:
dataFFeatures=dataFFeatures.apply(LabelEncoder().fit_transform)

In [47]:
len(dataIFeatures)

1530

In [48]:
t_model = Sequential()
t_model.add(Dense(256, input_shape=(83,)))
t_model.add(Dense(1024))
t_model.add(Dense(4096, activation=tf.nn.sigmoid))
t_model.compile(optimizer='adam',loss='categorical_crossentropy')
GF=t_model.predict(dataIFeatures)


In [49]:
t_model = Sequential()
t_model.add(Dense(256, input_shape=(43,)))
t_model.add(Dense(1024))
t_model.add(Dense(4096, activation=tf.nn.sigmoid))
t_model.compile(optimizer='adam',loss='categorical_crossentropy')
GF1=t_model.predict(dataFFeatures)


In [50]:
dI=pd.DataFrame(GF)
dF=pd.DataFrame(GF1)

In [51]:
ComFeat=dF.append(dI,ignore_index = True) 
ComT=DataFTarget["Sub_Cat"].append(DataITarget["Sub_Cat"],ignore_index = True)

In [52]:
Counter(ComT)

Counter({'Normal': 170,
         'Backdoor': 170,
         'Analysis': 170,
         'Fuzzers': 170,
         'Shellcode': 170,
         'Reconnaissance': 170,
         'Exploits': 170,
         'DoS': 170,
         'Worms': 170,
         'Generic': 170,
         'Mirai-Ackflooding': 170,
         'DoS-Synflooding': 170,
         'Scan Port OS': 170,
         'Mirai-Hostbruteforceg': 170,
         'Mirai-UDP Flooding': 170,
         'Mirai-HTTP Flooding': 170,
         'Scan Hostport': 170,
         'MITM ARP Spoofing': 170,
         'Normal_I': 170})

In [53]:
feat=np.array(ComFeat)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(feat, ComT, test_size=0.15, random_state=1, stratify=ComT, shuffle=True)

In [57]:
import time
start_time = time.time()

from keras import optimizers
import tensorflow.keras
tokenizer = tensorflow.keras.preprocessing.text.Tokenizer(num_words=5000,lower=False)
#tokenizer.fit_on_texts(X_train_res.values)
#print(tokenizer.word_index)  # To see the dicstionary
#X = tokenizer.texts_to_sequences(X_train_res.values)
#X = tensorflow.keras.preprocessing.sequence.pad_sequences(X_train_res)
#Deep Learning Network Structure
model_conv = Sequential()
model_conv.add(Embedding(5000,100, input_length=feat.shape[1]))
model_conv.add(Dropout(0.5))
model_conv.add(LSTM(100))
model_conv.add(Dense(19, activation='softmax'))
model_conv.compile(loss='categorical_crossentropy', optimizer='adam',   metrics=['accuracy','mae','mse',keras_metrics.precision(), keras_metrics.recall(),keras_metrics.f1_score()])
#Y = data.Reviewer_Score
Y = pd.get_dummies(ComT).values

X_train, X_valid, Y_train, Y_valid = train_test_split(feat,Y, test_size = 0.15, random_state =2)
batch_size=128
#Here we train the Network.

pred=model_conv.fit(X_train, Y_train, batch_size =batch_size, epochs =100, verbose =2,validation_data=(X_valid,Y_valid))
pred


print("--- %s seconds ---" % (time.time() - start_time))

Epoch 1/100


C:\Users\Sohail_Comp\anaconda3\lib\site-packages\keras_metrics\metrics.py:26: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return object.__getattribute__(self, name)


22/22 - 2242s - loss: 2.9420 - accuracy: 0.0685 - mae: 0.0997 - mse: 0.0498 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.9374 - val_accuracy: 0.0722 - val_mae: 0.0997 - val_mse: 0.0498 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 2242s/epoch - 102s/step
Epoch 2/100
22/22 - 2449s - loss: 2.8242 - accuracy: 0.1180 - mae: 0.0987 - mse: 0.0491 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.5920 - val_accuracy: 0.2351 - val_mae: 0.0963 - val_mse: 0.0476 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 2449s/epoch - 111s/step
Epoch 3/100
22/22 - 2455s - loss: 2.3649 - accuracy: 0.2302 - mae: 0.0936 - mse: 0.0459 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.2434 - val_accuracy: 0.2186 - val_mae: 0.0915 - val_mse: 0.0452 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 2455s/epoch - 11

Epoch 16/100
22/22 - 2706s - loss: 1.3611 - accuracy: 0.5002 - mae: 0.0675 - mse: 0.0327 - precision: 0.4753 - recall: 0.0395 - f1_score: 0.0729 - val_loss: 1.3586 - val_accuracy: 0.5113 - val_mae: 0.0671 - val_mse: 0.0325 - val_precision: 0.4634 - val_recall: 0.0390 - val_f1_score: 0.0720 - 2706s/epoch - 123s/step
Epoch 17/100
22/22 - 2896s - loss: 1.3001 - accuracy: 0.5056 - mae: 0.0660 - mse: 0.0319 - precision: 0.4610 - recall: 0.0420 - f1_score: 0.0769 - val_loss: 1.3556 - val_accuracy: 0.4990 - val_mae: 0.0660 - val_mse: 0.0324 - val_precision: 0.4544 - val_recall: 0.0458 - val_f1_score: 0.0832 - 2896s/epoch - 132s/step
Epoch 18/100
22/22 - 9715s - loss: 1.3365 - accuracy: 0.4980 - mae: 0.0663 - mse: 0.0325 - precision: 0.4633 - recall: 0.0509 - f1_score: 0.0918 - val_loss: 1.4395 - val_accuracy: 0.4722 - val_mae: 0.0669 - val_mse: 0.0333 - val_precision: 0.4726 - val_recall: 0.0537 - val_f1_score: 0.0964 - 9715s/epoch - 442s/step
Epoch 19/100
22/22 - 2758s - loss: 1.3297 - accur

Epoch 42/100
22/22 - 3345s - loss: 1.8655 - accuracy: 0.3599 - mae: 0.0838 - mse: 0.0403 - precision: 0.4958 - recall: 0.1410 - f1_score: 0.2195 - val_loss: 1.7660 - val_accuracy: 0.3588 - val_mae: 0.0805 - val_mse: 0.0386 - val_precision: 0.4958 - val_recall: 0.1393 - val_f1_score: 0.2175 - 3345s/epoch - 152s/step
Epoch 43/100
22/22 - 3673s - loss: 1.6685 - accuracy: 0.4131 - mae: 0.0783 - mse: 0.0374 - precision: 0.4958 - recall: 0.1376 - f1_score: 0.2154 - val_loss: 1.6740 - val_accuracy: 0.3918 - val_mae: 0.0771 - val_mse: 0.0374 - val_precision: 0.4958 - val_recall: 0.1361 - val_f1_score: 0.2135 - 3673s/epoch - 167s/step
Epoch 44/100
22/22 - 3314s - loss: 1.5741 - accuracy: 0.4317 - mae: 0.0752 - mse: 0.0361 - precision: 0.4958 - recall: 0.1345 - f1_score: 0.2116 - val_loss: 1.5702 - val_accuracy: 0.4577 - val_mae: 0.0744 - val_mse: 0.0357 - val_precision: 0.4958 - val_recall: 0.1330 - val_f1_score: 0.2097 - 3314s/epoch - 151s/step
Epoch 45/100
22/22 - 3361s - loss: 1.5351 - accur

KeyboardInterrupt: 

In [ ]:
import time
start_time = time.time()

from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,Embedding
from keras.models import Sequential
model_conv = Sequential()
model_conv.add(Embedding(50000, 100, input_length=feat.shape[1]))
model_conv.add(Conv1D(128, 3, activation='relu'))
model_conv.add(MaxPooling1D(pool_size=3))
model_conv.add(Activation('relu'))
model_conv.add(Dropout(rate=0.5))
model_conv.add(LSTM(128))
model_conv.add(Flatten())
model_conv.add(Dense(64))
model_conv.add(Dense(19, activation='softmax'))
model_conv.compile(loss='categorical_crossentropy', optimizer='adam',   metrics=['accuracy','mae','mse',keras_metrics.precision(), keras_metrics.recall(),keras_metrics.f1_score()])

#Here we train the Network.

pred2=model_conv.fit(X_train, Y_train, batch_size =batch_size, epochs =100, verbose =2,validation_data=(X_valid,Y_valid))
pred2

print("--- %s seconds ---" % (time.time() - start_time))

Epoch 1/100


C:\Users\Sohail_Comp\anaconda3\lib\site-packages\keras_metrics\metrics.py:26: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  return object.__getattribute__(self, name)


22/22 - 2190s - loss: 2.9345 - accuracy: 0.0761 - mae: 0.0996 - mse: 0.0498 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.9029 - val_accuracy: 0.0866 - val_mae: 0.0993 - val_mse: 0.0496 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 2190s/epoch - 100s/step
Epoch 2/100
22/22 - 2041s - loss: 2.8285 - accuracy: 0.1209 - mae: 0.0988 - mse: 0.0492 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.6195 - val_accuracy: 0.1773 - val_mae: 0.0972 - val_mse: 0.0479 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 2041s/epoch - 93s/step
Epoch 3/100
22/22 - 1466s - loss: 2.5756 - accuracy: 0.1650 - mae: 0.0965 - mse: 0.0476 - precision: 0.0000e+00 - recall: 0.0000e+00 - f1_score: 0.0000e+00 - val_loss: 2.3530 - val_accuracy: 0.1918 - val_mae: 0.0934 - val_mse: 0.0457 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00 - 1466s/epoch - 67s

Epoch 19/100
22/22 - 948s - loss: 1.0895 - accuracy: 0.5745 - mae: 0.0574 - mse: 0.0285 - precision: 0.5305 - recall: 0.0744 - f1_score: 0.1305 - val_loss: 1.0312 - val_accuracy: 0.6103 - val_mae: 0.0540 - val_mse: 0.0262 - val_precision: 0.5313 - val_recall: 0.0763 - val_f1_score: 0.1334 - 948s/epoch - 43s/step
Epoch 20/100
22/22 - 953s - loss: 1.0577 - accuracy: 0.5876 - mae: 0.0566 - mse: 0.0278 - precision: 0.5358 - recall: 0.0791 - f1_score: 0.1378 - val_loss: 1.0216 - val_accuracy: 0.5794 - val_mae: 0.0537 - val_mse: 0.0264 - val_precision: 0.5305 - val_recall: 0.0813 - val_f1_score: 0.1410 - 953s/epoch - 43s/step
Epoch 21/100
22/22 - 938s - loss: 1.0440 - accuracy: 0.5829 - mae: 0.0559 - mse: 0.0276 - precision: 0.5339 - recall: 0.0838 - f1_score: 0.1449 - val_loss: 1.0282 - val_accuracy: 0.5918 - val_mae: 0.0530 - val_mse: 0.0263 - val_precision: 0.5364 - val_recall: 0.0858 - val_f1_score: 0.1480 - 938s/epoch - 43s/step
Epoch 22/100
22/22 - 948s - loss: 1.0235 - accuracy: 0.592

Epoch 45/100
22/22 - 997s - loss: 0.6744 - accuracy: 0.7144 - mae: 0.0392 - mse: 0.0193 - precision: 0.6042 - recall: 0.1684 - f1_score: 0.2634 - val_loss: 0.8545 - val_accuracy: 0.6598 - val_mae: 0.0427 - val_mse: 0.0230 - val_precision: 0.6036 - val_recall: 0.1703 - val_f1_score: 0.2656 - 997s/epoch - 45s/step
Epoch 46/100
22/22 - 1040s - loss: 0.6740 - accuracy: 0.7213 - mae: 0.0397 - mse: 0.0193 - precision: 0.6024 - recall: 0.1721 - f1_score: 0.2677 - val_loss: 0.8523 - val_accuracy: 0.6804 - val_mae: 0.0419 - val_mse: 0.0222 - val_precision: 0.6044 - val_recall: 0.1737 - val_f1_score: 0.2699 - 1040s/epoch - 47s/step
Epoch 47/100
22/22 - 1108s - loss: 0.6677 - accuracy: 0.7129 - mae: 0.0389 - mse: 0.0192 - precision: 0.6065 - recall: 0.1756 - f1_score: 0.2723 - val_loss: 0.8479 - val_accuracy: 0.7052 - val_mae: 0.0394 - val_mse: 0.0213 - val_precision: 0.6073 - val_recall: 0.1763 - val_f1_score: 0.2733 - 1108s/epoch - 50s/step
Epoch 48/100
22/22 - 732s - loss: 0.6665 - accuracy: 0

Epoch 71/100
22/22 - 891s - loss: 0.5423 - accuracy: 0.7701 - mae: 0.0321 - mse: 0.0161 - precision: 0.6499 - recall: 0.2452 - f1_score: 0.3560 - val_loss: 0.9833 - val_accuracy: 0.6722 - val_mae: 0.0396 - val_mse: 0.0236 - val_precision: 0.6501 - val_recall: 0.2458 - val_f1_score: 0.3568 - 891s/epoch - 41s/step
Epoch 72/100
22/22 - 870s - loss: 0.4999 - accuracy: 0.8066 - mae: 0.0302 - mse: 0.0146 - precision: 0.6512 - recall: 0.2468 - f1_score: 0.3579 - val_loss: 0.8691 - val_accuracy: 0.7010 - val_mae: 0.0372 - val_mse: 0.0214 - val_precision: 0.6525 - val_recall: 0.2479 - val_f1_score: 0.3593 - 870s/epoch - 40s/step
Epoch 73/100
22/22 - 853s - loss: 0.4714 - accuracy: 0.8022 - mae: 0.0289 - mse: 0.0138 - precision: 0.6536 - recall: 0.2491 - f1_score: 0.3607 - val_loss: 0.8830 - val_accuracy: 0.6866 - val_mae: 0.0370 - val_mse: 0.0223 - val_precision: 0.6534 - val_recall: 0.2504 - val_f1_score: 0.3621 - 853s/epoch - 39s/step
Epoch 74/100
22/22 - 904s - loss: 0.4616 - accuracy: 0.809

In [60]:
yhat_classes = model_conv.predict(X_valid, verbose=0)
rounded_predictions=np.argmax(yhat_classes, axis=1)
rounded_labels=np.argmax(Y_valid, axis=1)
print(classification_report(rounded_labels,rounded_predictions))
print(confusion_matrix(rounded_labels,rounded_predictions))

              precision    recall  f1-score   support

           0       0.39      0.44      0.41        16
           1       0.90      0.72      0.80        25
           2       0.58      0.70      0.63        27
           3       1.00      1.00      1.00        24
           4       0.55      0.63      0.59        19
           5       0.96      0.90      0.93        29
           6       1.00      1.00      1.00        24
           7       1.00      0.92      0.96        38
           8       0.41      0.43      0.42        30
           9       0.32      0.33      0.33        24
          10       0.78      0.90      0.84        20
          11       0.83      0.83      0.83        24
          12       0.94      0.97      0.96        33
          13       1.00      0.94      0.97        31
          14       0.71      0.67      0.69        18
          15       0.48      0.58      0.52        19
          16       0.72      0.60      0.65        30
          17       0.91    

In [164]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  RandomForestClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))


0.8
                       precision    recall  f1-score   support

             Analysis       0.61      0.54      0.57        26
             Backdoor       0.76      0.73      0.75        26
                  DoS       0.71      0.88      0.79        25
      DoS-Synflooding       1.00      0.96      0.98        25
             Exploits       0.73      0.64      0.68        25
              Fuzzers       0.92      0.88      0.90        26
              Generic       0.96      1.00      0.98        25
    MITM ARP Spoofing       0.96      0.96      0.96        25
    Mirai-Ackflooding       0.43      0.35      0.38        26
  Mirai-HTTP Flooding       0.42      0.62      0.50        26
Mirai-Hostbruteforceg       0.92      0.92      0.92        25
   Mirai-UDP Flooding       0.86      0.69      0.77        26
               Normal       0.96      1.00      0.98        26
             Normal_I       0.96      1.00      0.98        26
       Reconnaissance       0.88      0.92      0.

In [165]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  ExtraTreesClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7938144329896907
                       precision    recall  f1-score   support

             Analysis       0.50      0.50      0.50        26
             Backdoor       0.69      0.69      0.69        26
                  DoS       0.73      0.88      0.80        25
      DoS-Synflooding       1.00      1.00      1.00        25
             Exploits       0.80      0.64      0.71        25
              Fuzzers       0.96      0.96      0.96        26
              Generic       0.96      1.00      0.98        25
    MITM ARP Spoofing       0.96      0.96      0.96        25
    Mirai-Ackflooding       0.36      0.31      0.33        26
  Mirai-HTTP Flooding       0.37      0.50      0.43        26
Mirai-Hostbruteforceg       0.96      0.92      0.94        25
   Mirai-UDP Flooding       0.82      0.69      0.75        26
               Normal       0.96      0.92      0.94        26
             Normal_I       0.96      1.00      0.98        26
       Reconnaissance       0.88   

In [166]:
from sklearn.linear_model import LogisticRegression
a=LogisticRegression(random_state=1000, solver='sag',multi_class='multinomial',C=2.0)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7917525773195876
                       precision    recall  f1-score   support

             Analysis       0.78      0.54      0.64        26
             Backdoor       0.79      0.85      0.81        26
                  DoS       0.71      0.96      0.81        25
      DoS-Synflooding       1.00      0.96      0.98        25
             Exploits       0.77      0.80      0.78        25
              Fuzzers       0.92      0.88      0.90        26
              Generic       0.96      1.00      0.98        25
    MITM ARP Spoofing       0.96      0.96      0.96        25
    Mirai-Ackflooding       0.38      0.46      0.41        26
  Mirai-HTTP Flooding       0.31      0.31      0.31        26
Mirai-Hostbruteforceg       0.96      0.92      0.94        25
   Mirai-UDP Flooding       0.82      0.69      0.75        26
               Normal       0.96      0.92      0.94        26
             Normal_I       0.96      1.00      0.98        26
       Reconnaissance       0.92   

C:\Users\Sohail_Comp\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [167]:
from sklearn.neighbors import KNeighborsClassifier
a = KNeighborsClassifier(n_neighbors=5)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7443298969072165
                       precision    recall  f1-score   support

             Analysis       0.62      0.62      0.62        26
             Backdoor       0.76      0.73      0.75        26
                  DoS       0.69      0.88      0.77        25
      DoS-Synflooding       1.00      0.96      0.98        25
             Exploits       0.59      0.64      0.62        25
              Fuzzers       0.85      0.88      0.87        26
              Generic       0.96      1.00      0.98        25
    MITM ARP Spoofing       0.80      0.96      0.87        25
    Mirai-Ackflooding       0.37      0.42      0.39        26
  Mirai-HTTP Flooding       0.42      0.42      0.42        26
Mirai-Hostbruteforceg       0.95      0.76      0.84        25
   Mirai-UDP Flooding       0.77      0.65      0.71        26
               Normal       0.96      0.85      0.90        26
             Normal_I       0.96      0.92      0.94        26
       Reconnaissance       0.86   

In [168]:
from sklearn.svm import SVC
a=SVC(kernel='linear', C=2.0)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7711340206185567
                       precision    recall  f1-score   support

             Analysis       0.55      0.46      0.50        26
             Backdoor       0.71      0.65      0.68        26
                  DoS       0.66      0.92      0.77        25
      DoS-Synflooding       1.00      0.96      0.98        25
             Exploits       0.77      0.68      0.72        25
              Fuzzers       0.96      0.92      0.94        26
              Generic       0.89      1.00      0.94        25
    MITM ARP Spoofing       0.92      0.96      0.94        25
    Mirai-Ackflooding       0.31      0.31      0.31        26
  Mirai-HTTP Flooding       0.30      0.35      0.32        26
Mirai-Hostbruteforceg       0.96      0.92      0.94        25
   Mirai-UDP Flooding       0.70      0.62      0.65        26
               Normal       0.96      0.96      0.96        26
             Normal_I       0.96      1.00      0.98        26
       Reconnaissance       0.88   

In [169]:
X_train, X_test, y_train, y_test = train_test_split(GF, DataITarget["Sub_Cat"], test_size=0.15, random_state=1, stratify=DataITarget["Sub_Cat"], shuffle=True)

In [170]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  RandomForestClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))


0.7739130434782608
                       precision    recall  f1-score   support

      DoS-Synflooding       1.00      1.00      1.00        26
    MITM ARP Spoofing       1.00      1.00      1.00        26
    Mirai-Ackflooding       0.36      0.36      0.36        25
  Mirai-HTTP Flooding       0.36      0.38      0.37        26
Mirai-Hostbruteforceg       0.96      0.92      0.94        26
   Mirai-UDP Flooding       0.77      0.65      0.71        26
             Normal_I       0.89      0.96      0.92        25
        Scan Hostport       0.84      0.84      0.84        25
         Scan Port OS       0.81      0.84      0.82        25

             accuracy                           0.77       230
            macro avg       0.78      0.77      0.77       230
         weighted avg       0.78      0.77      0.77       230

[[26  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  0]
 [ 0  0  9 13  1  2  0  0  0]
 [ 0  0 12 10  0  3  1  0  0]
 [ 0  0  0  0 24  0  2  0  0]
 [ 0  0  

In [171]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  ExtraTreesClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7565217391304347
                       precision    recall  f1-score   support

      DoS-Synflooding       1.00      1.00      1.00        26
    MITM ARP Spoofing       1.00      0.92      0.96        26
    Mirai-Ackflooding       0.23      0.24      0.24        25
  Mirai-HTTP Flooding       0.31      0.31      0.31        26
Mirai-Hostbruteforceg       0.86      0.92      0.89        26
   Mirai-UDP Flooding       0.74      0.65      0.69        26
             Normal_I       0.89      0.96      0.92        25
        Scan Hostport       0.92      0.88      0.90        25
         Scan Port OS       0.88      0.92      0.90        25

             accuracy                           0.76       230
            macro avg       0.76      0.76      0.76       230
         weighted avg       0.76      0.76      0.76       230

[[26  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  2  0  0  0  0]
 [ 0  0  6 15  1  3  0  0  0]
 [ 0  0 14  8  0  3  1  0  0]
 [ 0  0  0  0 24  0  2  0  0]
 [ 0  0  

In [172]:
from sklearn.linear_model import LogisticRegression
a=LogisticRegression(random_state=1000, solver='sag',multi_class='multinomial',C=2.0)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7347826086956522
                       precision    recall  f1-score   support

      DoS-Synflooding       1.00      1.00      1.00        26
    MITM ARP Spoofing       1.00      0.92      0.96        26
    Mirai-Ackflooding       0.30      0.40      0.34        25
  Mirai-HTTP Flooding       0.29      0.27      0.28        26
Mirai-Hostbruteforceg       0.85      0.85      0.85        26
   Mirai-UDP Flooding       0.80      0.62      0.70        26
             Normal_I       0.92      0.96      0.94        25
        Scan Hostport       0.80      0.80      0.80        25
         Scan Port OS       0.77      0.80      0.78        25

             accuracy                           0.73       230
            macro avg       0.75      0.73      0.74       230
         weighted avg       0.75      0.73      0.74       230

[[26  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  2  0  0  0  0]
 [ 0  0 10 12  1  2  0  0  0]
 [ 0  0 17  7  0  2  0  0  0]
 [ 0  0  0  1 22  0  2  0  1]
 [ 0  0  

C:\Users\Sohail_Comp\anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [173]:
from sklearn.neighbors import KNeighborsClassifier
a = KNeighborsClassifier(n_neighbors=5)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7043478260869566
                       precision    recall  f1-score   support

      DoS-Synflooding       1.00      1.00      1.00        26
    MITM ARP Spoofing       0.83      0.96      0.89        26
    Mirai-Ackflooding       0.32      0.40      0.36        25
  Mirai-HTTP Flooding       0.40      0.38      0.39        26
Mirai-Hostbruteforceg       0.95      0.69      0.80        26
   Mirai-UDP Flooding       0.76      0.62      0.68        26
             Normal_I       0.96      0.96      0.96        25
        Scan Hostport       0.60      0.72      0.65        25
         Scan Port OS       0.65      0.60      0.63        25

             accuracy                           0.70       230
            macro avg       0.72      0.70      0.71       230
         weighted avg       0.72      0.70      0.71       230

[[26  0  0  0  0  0  0  0  0]
 [ 0 25  0  0  1  0  0  0  0]
 [ 0  3 10 10  0  2  0  0  0]
 [ 0  0 15 10  0  1  0  0  0]
 [ 0  2  1  0 18  0  1  3  1]
 [ 0  0  

In [174]:
from sklearn.svm import SVC
a=SVC(kernel='linear', C=2.0)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7565217391304347
                       precision    recall  f1-score   support

      DoS-Synflooding       1.00      1.00      1.00        26
    MITM ARP Spoofing       1.00      1.00      1.00        26
    Mirai-Ackflooding       0.30      0.36      0.33        25
  Mirai-HTTP Flooding       0.33      0.31      0.32        26
Mirai-Hostbruteforceg       0.92      0.92      0.92        26
   Mirai-UDP Flooding       0.77      0.65      0.71        26
             Normal_I       0.92      0.96      0.94        25
        Scan Hostport       0.80      0.80      0.80        25
         Scan Port OS       0.80      0.80      0.80        25

             accuracy                           0.76       230
            macro avg       0.76      0.76      0.76       230
         weighted avg       0.76      0.76      0.76       230

[[26  0  0  0  0  0  0  0  0]
 [ 0 26  0  0  0  0  0  0  0]
 [ 0  0  9 12  1  3  0  0  0]
 [ 0  0 16  8  0  2  0  0  0]
 [ 0  0  0  0 24  0  2  0  0]
 [ 0  0  

In [175]:
X_train, X_test, y_train, y_test = train_test_split(GF1, DataFTarget["Sub_Cat"], test_size=0.15, random_state=1, stratify=DataFTarget["Sub_Cat"], shuffle=True)

In [176]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  RandomForestClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))


0.803921568627451
                precision    recall  f1-score   support

      Analysis       0.48      0.44      0.46        25
      Backdoor       0.68      0.65      0.67        26
           DoS       0.72      0.92      0.81        25
      Exploits       0.88      0.81      0.84        26
       Fuzzers       0.85      0.92      0.88        25
       Generic       1.00      1.00      1.00        26
        Normal       0.93      1.00      0.96        25
Reconnaissance       0.90      0.69      0.78        26
     Shellcode       0.79      0.73      0.76        26
         Worms       0.81      0.88      0.85        25

      accuracy                           0.80       255
     macro avg       0.80      0.80      0.80       255
  weighted avg       0.80      0.80      0.80       255

[[11  8  3  2  0  0  0  1  0  0]
 [ 8 17  0  0  0  0  1  0  0  0]
 [ 1  0 23  0  0  0  0  1  0  0]
 [ 0  0  5 21  0  0  0  0  0  0]
 [ 2  0  0  0 23  0  0  0  0  0]
 [ 0  0  0  0  0 26  0  0  0  

In [177]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
a =  ExtraTreesClassifier(n_estimators=200, random_state=2,max_depth=150) 
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.8156862745098039
                precision    recall  f1-score   support

      Analysis       0.62      0.52      0.57        25
      Backdoor       0.71      0.77      0.74        26
           DoS       0.71      0.88      0.79        25
      Exploits       0.88      0.81      0.84        26
       Fuzzers       0.92      0.88      0.90        25
       Generic       1.00      1.00      1.00        26
        Normal       0.93      1.00      0.96        25
Reconnaissance       0.90      0.69      0.78        26
     Shellcode       0.75      0.69      0.72        26
         Worms       0.77      0.92      0.84        25

      accuracy                           0.82       255
     macro avg       0.82      0.82      0.81       255
  weighted avg       0.82      0.82      0.81       255

[[13  8  3  0  0  0  0  1  0  0]
 [ 5 20  0  0  0  0  1  0  0  0]
 [ 2  0 22  0  0  0  0  1  0  0]
 [ 0  0  5 21  0  0  0  0  0  0]
 [ 1  0  0  2 22  0  0  0  0  0]
 [ 0  0  0  0  0 26  0  0  0 

In [178]:
from sklearn.neighbors import KNeighborsClassifier
a = KNeighborsClassifier(n_neighbors=5)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.7843137254901961
                precision    recall  f1-score   support

      Analysis       0.70      0.64      0.67        25
      Backdoor       0.76      0.73      0.75        26
           DoS       0.67      0.88      0.76        25
      Exploits       0.68      0.73      0.70        26
       Fuzzers       0.83      0.80      0.82        25
       Generic       1.00      1.00      1.00        26
        Normal       0.96      0.96      0.96        25
Reconnaissance       0.89      0.65      0.76        26
     Shellcode       0.69      0.69      0.69        26
         Worms       0.73      0.76      0.75        25

      accuracy                           0.78       255
     macro avg       0.79      0.78      0.78       255
  weighted avg       0.79      0.78      0.78       255

[[16  6  3  0  0  0  0  0  0  0]
 [ 6 19  0  1  0  0  0  0  0  0]
 [ 1  0 22  1  0  0  0  1  0  0]
 [ 0  0  7 19  0  0  0  0  0  0]
 [ 0  0  0  4 20  0  0  0  1  0]
 [ 0  0  0  0  0 26  0  0  0 

In [179]:
from sklearn.svm import SVC
a=SVC(kernel='linear', C=2.0)
a_pred = a.fit(X_train, y_train)
pred=a_pred.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.796078431372549
                precision    recall  f1-score   support

      Analysis       0.61      0.44      0.51        25
      Backdoor       0.71      0.77      0.74        26
           DoS       0.65      0.96      0.77        25
      Exploits       0.77      0.65      0.71        26
       Fuzzers       0.96      0.92      0.94        25
       Generic       1.00      1.00      1.00        26
        Normal       0.96      1.00      0.98        25
Reconnaissance       0.79      0.73      0.76        26
     Shellcode       0.75      0.58      0.65        26
         Worms       0.77      0.92      0.84        25

      accuracy                           0.80       255
     macro avg       0.80      0.80      0.79       255
  weighted avg       0.80      0.80      0.79       255

[[11  8  3  2  0  0  0  1  0  0]
 [ 5 20  0  0  0  0  1  0  0  0]
 [ 0  0 24  1  0  0  0  0  0  0]
 [ 0  0  8 17  0  0  0  1  0  0]
 [ 0  0  0  1 23  0  0  0  0  1]
 [ 0  0  0  0  0 26  0  0  0  